<a href="https://colab.research.google.com/github/Honggu12/Machine-Learning/blob/main/01_numpy%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

파이썬의 list와 numpy의 ndarray의 차이점

* 파이썬의 리스트보다 속도가 훨씬 빠르다.
* 파이썬의 리스트보다 배열을 훨씬 크게 다룰 수 있다.


In [ ]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
# 2차원 배열 만들기 with Python의 list

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
type(arr2)

numpy.ndarray

파이썬 리스트는 여러 형태를 담을 수 있지만
넘파이는 숫자 데이터만 담을 수 있다.

In [ ]:
arr = np.arange(10) # 0 - 9 까지 들어있는 숫자 배열
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1, 10, 2) # 1부터 9까지 2씩 띄워 가면서
arr

array([1, 3, 5, 7, 9])

다차원 배열

np.zeros
지정한 차원에 모든 원소를 0으로 채운다.

np.ones
지정한 차원에 모든 원소를 1로 채운다.

np.full
지정한 차원의 배열에 원하는 수를 채워 넣는다.

-------------------------------------------------------

단위 행렬 만들기

np.eye
대각선이 1인 단위행렬임.

np.linspace(a, b, c)
a부터 b까지 c개의 구간 만들기

-------------------------------------------
랜덤을 사용하기 위한 numpy

-보통 랜덤한 배열은 딥러닝에서 매개변수의 초기화를 하기 위해 사용한다.
-딥러닝에서는 일반적으로 Xavier 초기값, He초기값, 정규분포 초깃값을 계산해 준다.

In [ ]:
# 일반적인 랜덤값만 만들기( 균등분포x , 정규분포x)
np.random.rand(2, 3) # 0-1사이의 랜덤값 만들기

array([[0.05539115, 0.80764863, 0.45195337],
       [0.11850968, 0.32925119, 0.1281851 ]])

In [ ]:
# 정규분포 랜덤값 만들기
np.random.randn(10)

array([-0.41654668,  1.97313058,  1.57055529,  0.14836724, -1.30346284,
       -0.84353957, -1.43131351, -0.37133635, -0.8585284 , -0.04716257])

In [ ]:
np.random.randn(3, 4, 2)

array([[[-1.31022564, -0.05543212],
        [-1.31294524,  0.49562248],
        [-1.47736296, -0.2073577 ],
        [-0.14162749, -0.12465881]],

       [[-0.48595961, -0.9709123 ],
        [ 1.3873015 , -1.05693898],
        [-1.34638052, -2.49098303],
        [ 0.20393527, -0.09879504]],

       [[-0.31754257,  1.2817342 ],
        [ 0.24479823,  1.31952327],
        [ 2.19078833,  0.00490066],
        [-0.82437475, -1.41368235]]])

In [ ]:
# 균등 분포 만들기
np.random.uniform(1.0, 3.0, size=(4, 5)) # 사이즈를 통해서 배열의 형상(shape) 지정

array([[2.2338063 , 1.41104544, 2.86116397, 1.46145285, 1.32459212],
       [1.9548758 , 2.95536461, 2.25224456, 1.43589066, 2.22150229],
       [1.9048061 , 1.95511145, 2.86648375, 1.70129907, 2.13718602],
       [1.02303184, 2.21710401, 1.99351776, 1.68024162, 1.94328049]])

정수 랜덤 만들기

In [ ]:
np.random.randint(1, 100, size=(5))

array([76, 72, 62, 33, 73])

In [ ]:
np.random.randint(1, 100, size=(5, 1))

array([[28],
       [10],
       [93],
       [47],
       [35]])

In [ ]:
np.random.randint(1, 100, size=(3, 4, 5))

array([[[71, 29, 34, 68, 97],
        [12, 64, 13,  9, 95],
        [93, 64, 96, 59, 18],
        [61, 48, 20,  2, 73]],

       [[88, 65, 31,  5, 48],
        [47, 75, 18, 50,  1],
        [85, 33, 68, 68, 62],
        [35, 85, 32, 75, 49]],

       [[16, 44, 98, 79, 14],
        [71, 60,  2, 95, 12],
        [52, 15,  2, 69, 66],
        [41, 83, 96, 17, 48]]])

In [ ]:
#1차원 배열에서 랜덤 샘플링 하기 (중복 안됨)
#미니 배치를 만들 때 사용된다.
np.random.choice(100, size=(3, 4))

array([[97, 47, 49, 54],
       [55, 29, 10,  4],
       [56, 53, 25, 96]])

In [ ]:
arr = np.arange(1, 6)
arr
np.random.choice(arr, size=(2, 2), replace=False) # True이면 원소를 중복 추출, False이면 중복 추출 X

array([[5, 1],
       [2, 3]])

인덱스와 슬라이싱

In [ ]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0][2]

3

In [ ]:
arr[0, 2]

3

In [ ]:
arr[:,2] #

array([3, 8])

In [ ]:
arr = np.arange(36).reshape(3, 4, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
arr[:, :2, :2]

array([[[ 0,  1],
        [ 3,  4]],

       [[12, 13],
        [15, 16]],

       [[24, 25],
        [27, 28]]])

In [ ]:
arr[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
# 배열의 차원과 형상

# * 형상(shape)
# * 차원수(ndim)

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

# 차원수 늘리기
# 이미지 분석(CNN) 레이어를 사용하기 위해서는 필수적으로 알아야 한다.

In [ ]:
# Tensorflow 기준으로 CNN에 사용되어지는 배열의 형상은 항상 다음과 같다.
arr2 = arr[np.newaxis,  :, :, np.newaxis] # arr[이미지개수, 가로길이, 세로길이, rgb채널 개수]
arr2.shape
# 이러한 형식을 사용하는게 아래의 방식들보다 더 좋음(좀더 명확함)

(1, 3, 4, 1)

In [ ]:
arr2.ndim

4

In [ ]:
arr2

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

동영상은 4차원 데이터

In [ ]:
arr3 = np.squeeze(arr2)
arr3.shape

(3, 4)

In [ ]:
arr4 = arr[np.newaxis, ..., np.newaxis]
arr4.shape

(1, 3, 4, 1)

# 배열의 형상 (shape)바꾸기
np.newaxis를 활용해서 축을 추가한다. (차원수를 늘린다.)
-평탄화
 ravel()
 flatten()

-형상변환
  reshape()


In [ ]:
x = np.arange(15).reshape(3, 5)
print(x)
x.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [ ]:
# ravel : 평탄화 시킨 참조 배열을 낸다. (view 또는 Reference를 만들어 낸다.)
# flatten : 평탄화 시킨 복사 배열을 만들어 낸다.(복사본을 만들어 낸다.)

temp = np.ravel(x)
print(temp)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [ ]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
temp2 = y.flatten() #  y를 1차원으로 쭉 펴낸 배열을 새롭게 만들어 낸다.
print(temp2)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
temp2[0] = 100
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# reshape (배열의 형상을 바꾸기)
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(2, 2, -1) #-1은 조커. 2번 이상 사용 불가능

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
x.reshape(3, -1)

ValueError: ignored

In [ ]:
x.reshape(-1, 5).shape

(3, 5)

In [ ]:
x.reshape(2, -1, 5).shape

(2, 2, 5)

# 브로드 캐스팅
차원수가 다른 배열끼리의 연선

In [ ]:
x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3, 5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1.32822509  0.75628182 -1.07725193 -0.80239151 -0.05806559]
 [-1.06491825  2.03653689 -1.08014213  0.38617111 -0.86406204]
 [ 1.10792593 -0.43636283  1.30072439 -0.21913573 -0.58166402]]


In [ ]:
x + y

array([[ 1.32822509,  1.75628182,  0.92274807,  2.19760849,  3.94193441],
       [ 3.93508175,  8.03653689,  5.91985787,  8.38617111,  8.13593796],
       [11.10792593, 10.56363717, 13.30072439, 12.78086427, 13.41833598]])

In [ ]:
x * y

array([[ 0.        ,  0.75628182, -2.15450386, -2.40717454, -0.23226235],
       [-5.32459126, 12.21922134, -7.56099489,  3.08936886, -7.77655832],
       [11.07925933, -4.79999112, 15.60869265, -2.84876443, -8.1432963 ]])

In [ ]:
x * 2 # x는 배열, 2는 스칼라값, 스칼라값이 브로드 캐스팅된다.

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
a = np.arange(12).reshape(4, 3) # (4, 3)
b = np.arange(100, 103) # (3, )
c = np.arange(1000, 1004) # (4, )
d = b.reshape(1, 3) # (1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + c

ValueError: ignored

In [ ]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

전치 행렬 만들기

In [ ]:
e = np.arange(6).reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
e.T

array([[0, 3],
       [1, 4],
       [2, 5]])