<a href="https://colab.research.google.com/github/Honggu12/Machine-Learning/blob/main/02_%ED%96%89%EB%A0%AC%EA%B3%BC_%EC%8B%A0%EA%B2%BD%EB%A7%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4])
B = np.arange(1, 7).reshape(3, 2)

In [ ]:
A.shape

(4,)

In [ ]:
B.shape

(3, 2)

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)

In [ ]:
A.shape

(2, 3)

In [ ]:
B.shape

(3, 2)

A와 B의 내적을 구할 수 있나요?yes

In [ ]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

B와 A의 내적을 구할수 있나요? yes

In [ ]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [ ]:
C = np.arange(1, 5).reshape(2, 2)

A와 C의 내적을 구할 수 있나요?No

In [ ]:
A.shape

(2, 3)

In [ ]:
C.shape

(2, 2)

In [ ]:
np.dot(A, C)

ValueError: ignored

C와 A의 내적 구할 수 있나요?Yes

In [ ]:
np.dot(C, A)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
D = np.arange(1, 3)

In [ ]:
D

array([1, 2])

In [ ]:
D.shape

(2,)

A와D의 내적 가능?

In [ ]:
A.shape, D.shape

((2, 3), (2,))

D와 A의 내적 가능? yes

In [ ]:
np.dot(D, A)

array([ 9, 12, 15])

In [ ]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],
               [0.2, 0.4, 0.6] ]) # 2개의 입력을 받는 3개의 뉴런 - 1층의 구조

B1 = np.array( [0.1, 0.2, 0.3] )


In [ ]:
X.shape, W1.shape, B1.shape

((2,), (2, 3), (3,))

In [ ]:
Z1 = np.dot(X, W1) + B1
Z1

array([0.3, 0.7, 1.1])

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
A1 = sigmoid(Z1)
A1

array([0.57444252, 0.66818777, 0.75026011])

In [ ]:
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]]) # 3개의 입력을 받는 2개의 뉴런

B2 = np.array([0.1, 0.2])

Z2 = np.dot(A1, W2) + B2
A2 = sigmoid(Z2)
A2

array([0.62624937, 0.7710107 ])

In [ ]:
# 항등함수
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

Z3 = np.dot(A2, W3) + B3
Y = identity_function(Z3)

Y

array([0.31682708, 0.69627909])